main: me.asakura_kukii.siegeweapon.main.Main
version: 0.0.2
api-version: 1.18
name: SiegeWeapon
commands:
  SiegeWeapon:
    description: Main command for SiegeWeapon
    aliases: [sw]
permissions:
  siegeweapon.admin:
    description: 'Gives access to all admin commands for QAM'
    children:
      siegeweapon.debugmessages: true
      siegeweapon.reload: true
      siegeweapon.item: true
      siegeweapon.util: true
softdepend: [ProtocolLib]
author:
   Asakura_kukii